const state={characters:[],active:0,quest:null,node:null,flags:{},pendingCheck:null,voice:false};
const creationRolls={};
const slotModes={};
const abilities=['FOR','DES','CON','INT','SAB','CAR'];
const labels={FOR:'Força',DES:'Destreza',CON:'Constituição',INT:'Inteligência',SAB:'Sabedoria',CAR:'Carisma'};
const hitDie={Barbaro:12,Bárbaro:12,Guerreiro:10,Ranger:10,Paladino:10,Clérigo:8,Druida:8,Monge:8,Ladino:8,Bardo:8,Bruxo:8,Feiticeiro:6,Mago:6};
function $(id){return document.getElementById(id)}
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active')}
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function mod(v){return Math.floor((Number(v||10)-10)/2)} function fmt(n){return (n>=0?'+':'')+n}
function prof(level){return 2+Math.floor((Math.max(1,level)-1)/4)}
function armorCA(type,dex,shield){let ca=10+dex;if(type==='Couro')ca=11+dex;if(type==='Camisão de malha')ca=13+Math.min(dex,2);if(type==='Cota de malha')ca=16;if(type==='Placas')ca=18;if(shield)ca+=2;return ca}
function classHP(classes,con){let hp=0;classes.forEach((c,ci)=>{const d=hitDie[c.name]||8;for(let i=0;i<c.level;i++)hp+=(ci===0&&i===0?d:Math.floor(d/2)+1)+con});return Math.max(1,hp)}
function calc(c){const level=c.classes.reduce((a,x)=>a+x.level,0);const dex=mod(c.attrs.DES),con=mod(c.attrs.CON);c.level=level;c.prof=prof(level);c.ini=dex;c.ca=armorCA(c.armor,dex,c.shield);c.hpMax=classHP(c.classes,con);c.hp=c.hpMax;c.speed=9;c.hitDice=c.classes.map(x=>`${x.level}d${hitDie[x.name]||8}`).join(' + ');c.cls=c.classes.map(x=>`${x.name} ${x.level}`).join(' / ');return c}
function savedCharacters(){try{const x=JSON.parse(localStorage.getItem('valedouro.characters')||'[]');return Array.isArray(x)?x:[]}catch{return []}}
function playerCount(){const n=+$('playerCount').value;$('charForms').innerHTML='';for(let i=0;i<n;i++){slotModes[i]='create';creationRolls[i]={index:0,attrs:{}};$('charForms').insertAdjacentHTML('beforeend',charSlot(i));renderSlot(i)}}
function charSlot(i){return `<div class="char-card" id="slot${i}"><div class="slot-head"><h3>Personagem ${i+1}</h3><div class="row"><button class="btn primary" id="modeCreate${i}" onclick="setSlotMode(${i},'create')">Criar nova ficha</button><button class="btn" id="modeLoad${i}" onclick="setSlotMode(${i},'load')">Carregar ficha salva</button></div></div><div id="slotBody${i}"></div></div>`}
function setSlotMode(i,mode){slotModes[i]=mode;document.querySelectorAll(`#slot${i} .slot-head .btn`).forEach(b=>b.classList.remove('primary'));$(mode==='create'?`modeCreate${i}`:`modeLoad${i}`).classList.add('primary');renderSlot(i)}
function renderSlot(i){if(slotModes[i]==='load') renderLoadSlot(i); else renderCreateSlot(i)}
function renderLoadSlot(i){const saved=savedCharacters();const body=$(`slotBody${i}`);if(!saved.length){body.innerHTML=`<div class="empty-state"><p>Nenhuma ficha salva neste navegador.</p><p class="muted">Crie uma ficha primeiro. Depois ela poderá ser reutilizada em novas partidas.</p><button class="btn" onclick="setSlotMode(${i},'create')">Criar personagem</button></div>`;return}
 body.innerHTML=`<div class="load-grid"><div class="field"><label>Ficha salva</label><select id="saved${i}" onchange="previewSaved(${i})">${saved.map((c,k)=>`<option value="${k}">${esc(c.name)} — ${esc(c.cls||'personagem')}</option>`).join('')}</select></div><div id="savedPreview${i}"></div></div>`;previewSaved(i)}
function previewSaved(i){const saved=savedCharacters();const c=saved[+$(`saved${i}`).value||0];$(`savedPreview${i}`).innerHTML=c?`<div class="saved-preview"><strong>${esc(c.name)}</strong><span>${esc(c.race)} • ${esc(c.cls)}</span><span>CA ${c.ca} • PV ${c.hpMax} • Nível ${c.level}</span></div>`:''}
function renderCreateSlot(i){const r=creationRolls[i]||{index:0,attrs:{}};creationRolls[i]=r;const complete=r.index>=abilities.length;const current=abilities[Math.min(r.index,abilities.length-1)];$(`slotBody${i}`).innerHTML=`<div class="grid2"><div><div class="field"><label>Nome</label><input id="name${i}" value=""></div><div class="field"><label>Povo</label><select id="race${i}"><option>Humano</option><option>Elfo</option><option>Anão</option><option>Halfling</option></select></div><div class="field"><label>Histórico</label><input id="bg${i}" value="Viajante"></div><div class="row"><div class="field"><label>Classe inicial</label><select id="c1${i}">${classOpts('Guerreiro')}</select></div><div class="field"><label>Nível</label><input id="l1${i}" type="number" min="1" max="20" value="1"></div></div><div class="row"><div class="field"><label>Multiclasse</label><select id="c2${i}"><option value="">— nenhuma —</option>${classOpts('Ranger')}</select></div><div class="field"><label>Nível</label><input id="l2${i}" type="number" min="0" max="19" value="0"></div></div><div class="row"><div class="field"><label>Armadura</label><select id="armor${i}"><option>Nenhuma</option><option>Couro</option><option selected>Camisão de malha</option><option>Cota de malha</option><option>Placas</option></select></div><label class="checkline"><input id="shield${i}" type="checkbox"> Escudo</label></div></div><div><div class="attribute-builder"><div class="builder-head"><div><h4>Atributos</h4><p class="muted">Os valores são gerados por dados: 4d6, descartando o menor. Não podem ser digitados manualmente.</p></div><button class="btn small" onclick="resetAttributes(${i})">Reiniciar atributos</button></div><div class="ability-grid">${abilities.map(a=>`<div class="ability ${a===current&&!complete?'current':''}"><small>${labels[a]}</small><b>${r.attrs[a]??'—'}</b><span>${r.attrs[a]!=null?fmt(mod(r.attrs[a])):'aguardando'}</span></div>`).join('')}</div><div class="dice-workbench"><div id="rollPrompt${i}" class="roll-prompt">${complete?'Atributos concluídos.':`Role para <strong>${labels[current]}</strong>`}</div><div id="diceTray${i}" class="dice-tray">${r.lastDice?r.lastDice.map((d,k)=>`<div class="mini-d6 ${k===r.discardIndex?'discarded':''}">${d}</div>`).join(''):'<span class="muted">Os quatro d6 aparecerão aqui.</span>'}</div><button id="attrRollBtn${i}" class="btn primary" onclick="rollAttribute(${i})" ${complete?'disabled':''}>${complete?'Atributos definidos':`🎲 Rolar 4d6 para ${labels[current]}`}</button>${r.lastTotal!=null?`<div class="roll-summary">Resultado anterior: ${r.lastDice.join(' + ')} → descarta ${r.lastDice[r.discardIndex]} → <strong>${r.lastTotal}</strong></div>`:''}</div></div></div></div>`}
function rollAttribute(i){const r=creationRolls[i];if(!r||r.index>=abilities.length)return;const dice=Array.from({length:4},()=>Math.floor(Math.random()*6)+1);let min=0;for(let k=1;k<dice.length;k++)if(dice[k]<dice[min])min=k;const total=dice.reduce((a,b)=>a+b,0)-dice[min];const a=abilities[r.index];r.attrs[a]=total;r.lastDice=dice;r.discardIndex=min;r.lastTotal=total;r.index++;renderCreateSlotPreserve(i)}
function renderCreateSlotPreserve(i){const vals={name:$(`name${i}`)?.value,race:$(`race${i}`)?.value,bg:$(`bg${i}`)?.value,c1:$(`c1${i}`)?.value,l1:$(`l1${i}`)?.value,c2:$(`c2${i}`)?.value,l2:$(`l2${i}`)?.value,armor:$(`armor${i}`)?.value,shield:$(`shield${i}`)?.checked};renderCreateSlot(i);if(vals.name!=null){$(`name${i}`).value=vals.name;$(`race${i}`).value=vals.race;$(`bg${i}`).value=vals.bg;$(`c1${i}`).value=vals.c1;$(`l1${i}`).value=vals.l1;$(`c2${i}`).value=vals.c2;$(`l2${i}`).value=vals.l2;$(`armor${i}`).value=vals.armor;$(`shield${i}`).checked=vals.shield}}
function resetAttributes(i){const vals={name:$(`name${i}`)?.value,race:$(`race${i}`)?.value,bg:$(`bg${i}`)?.value,c1:$(`c1${i}`)?.value,l1:$(`l1${i}`)?.value,c2:$(`c2${i}`)?.value,l2:$(`l2${i}`)?.value,armor:$(`armor${i}`)?.value,shield:$(`shield${i}`)?.checked};creationRolls[i]={index:0,attrs:{}};renderCreateSlot(i);if(vals.name!=null){$(`name${i}`).value=vals.name;$(`race${i}`).value=vals.race;$(`bg${i}`).value=vals.bg;$(`c1${i}`).value=vals.c1;$(`l1${i}`).value=vals.l1;$(`c2${i}`).value=vals.c2;$(`l2${i}`).value=vals.l2;$(`armor${i}`).value=vals.armor;$(`shield${i}`).checked=vals.shield}}
function classOpts(sel){return ['Guerreiro','Ranger','Bárbaro','Paladino','Clérigo','Druida','Monge','Ladino','Bardo','Bruxo','Feiticeiro','Mago'].map(x=>`<option ${x===sel?'selected':''}>${x}</option>`).join('')}
function collectChars(){const n=+$('playerCount').value;const result=[];const saved=savedCharacters();for(let i=0;i<n;i++){if(slotModes[i]==='load'){const c=saved[+$(`saved${i}`)?.value||0];if(!c){alert(`Selecione uma ficha salva para o Personagem ${i+1}.`);return}result.push(JSON.parse(JSON.stringify(c)));continue}
 const r=creationRolls[i];if(!r||r.index<abilities.length){alert(`Role os seis atributos do Personagem ${i+1} antes de validar a ficha.`);return}const l1=Math.max(1,+$(`l1${i}`).value||1),c2=$(`c2${i}`).value,l2=+$(`l2${i}`).value||0;if(l1+l2>20){alert(`O nível total do Personagem ${i+1} não pode ultrapassar 20.`);return}if(c2&&c2===$(`c1${i}`).value){alert(`No Personagem ${i+1}, escolha uma classe diferente para multiclasse ou deixe "nenhuma".`);return}
 const classes=[{name:$(`c1${i}`).value,level:l1}];if(c2&&l2>0)classes.push({name:c2,level:l2});const name=$(`name${i}`).value.trim();if(!name){alert(`Informe o nome do Personagem ${i+1}.`);return}result.push(calc({name,race:$(`race${i}`).value,background:$(`bg${i}`).value,classes,attrs:{...r.attrs},armor:$(`armor${i}`).value,shield:$(`shield${i}`).checked}))}
 state.characters=result;saveChars();showReview()}
function saveChars(){const existing=savedCharacters();const map=new Map(existing.map(c=>[`${c.name}|${c.cls}`,c]));state.characters.forEach(c=>map.set(`${c.name}|${c.cls}`,c));localStorage.setItem('valedouro.characters',JSON.stringify([...map.values()]))}
function loadChars(){state.characters=savedCharacters()}
function sheet(c){return `<h2>${esc(c.name)}</h2><p>${esc(c.race)} • <strong>${esc(c.cls)}</strong> • nível total ${c.level}</p><div class="stat-grid"><div class="stat">CA<b>${c.ca}</b></div><div class="stat">PV<b>${c.hp}/${c.hpMax}</b></div><div class="stat">Iniciativa<b>${fmt(c.ini)}</b></div><div class="stat">Proficiência<b>${fmt(c.prof)}</b></div><div class="stat">Deslocamento<b>${c.speed} m</b></div><div class="stat">Dados de Vida<b style="font-size:15px">${esc(c.hitDice)}</b></div></div><div class="ability-grid">${abilities.map(a=>`<div class="ability"><small>${labels[a]}</small><b>${c.attrs[a]}</b><span>${fmt(mod(c.attrs[a]))}</span></div>`).join('')}</div><div class="sheet-cols"><div class="sheet-section"><h4>Classes</h4><div class="chips">${c.classes.map(x=>`<span>${esc(x.name)} ${x.level}</span>`).join('')}</div><p><strong>Armadura:</strong> ${esc(c.armor)} ${c.shield?'+ escudo':''}</p></div><div class="sheet-section"><h4>Identidade</h4><p><strong>Povo:</strong> ${esc(c.race)}</p><p><strong>Histórico:</strong> ${esc(c.background||'—')}</p></div></div>`}
function openSheet(i){$('sheetContent').innerHTML=sheet(state.characters[i]);$('sheetModal').classList.add('active')}
function closeSheet(){$('sheetModal').classList.remove('active')}
function showReview(){const el=$('reviewCards');el.innerHTML=state.characters.map((c,i)=>`<div class="char-card">${sheet(c)}<button class="btn" onclick="openSheet(${i})">Abrir ficha</button></div>`).join('');show('review')}
function showLibrary(){loadChars();$('library').innerHTML=state.characters.length?state.characters.map((c,i)=>`<div class="char-card"><h3>${esc(c.name)}</h3><p>${esc(c.cls)}</p><p>CA ${c.ca} • PV ${c.hpMax}</p><button class="btn" onclick="openSheet(${i})">Ficha</button></div>`).join(''):'<p class="muted">Nenhum personagem salvo neste navegador.</p>';show('characters')}
function startQuest(){if(!state.characters.length){alert('Crie pelo menos um personagem.');return}state.quest=Q01;state.node=Q01.start;state.flags={};state.pendingCheck=null;state.active=0;$('party').innerHTML=state.characters.map((c,i)=>`<div class="pc ${i===0?'selected':''}" onclick="selectPC(${i})"><strong>${esc(c.name)}</strong><small>${esc(c.cls)}</small><small>CA ${c.ca} • PV ${c.hp}/${c.hpMax}</small></div>`).join('');$('story').innerHTML='';selectPC(0);show('game');renderNode(true)}
function selectPC(i){state.active=i;document.querySelectorAll('.pc').forEach((x,j)=>x.classList.toggle('selected',i===j));$('activeName').textContent=state.characters[i]?.name||'—'}
function addStory(text,cls='master'){$('story').insertAdjacentHTML('beforeend',`<div class="entry ${cls}"><strong>${cls==='master'?'Mestre':'Sistema'}:</strong> ${esc(text)}</div>`);$('story').scrollTop=999999}
function renderNode(initial=false){const n=state.quest.nodes[state.node];if(!n)return;addStory(n.text);$('options').innerHTML='';$('rollbox').classList.remove('active');if(n.complete){$('questStatus').textContent='Concluída';saveGame();return}n.options.forEach((o,idx)=>{const b=document.createElement('button');b.className='btn';b.textContent=o.label;b.onclick=()=>choose(o);$('options').appendChild(b)});$('questStatus').textContent=`${state.quest.title} • Cena: ${state.node}`;saveGame()}
function choose(o){if(o.set)Object.assign(state.flags,o.set);if(o.check){state.pendingCheck=o.check;$('rollbox').classList.add('active');$('rollText').textContent=`Teste: ${o.check.skill||labels[o.check.ability]||o.check.ability} • CD ${o.check.dc}`;$('options').innerHTML='';return}state.node=o.next;renderNode()}
function rollCheck(){const c=state.characters[state.active];const chk=state.pendingCheck;if(!chk)return;const d=Math.floor(Math.random()*20)+1;const bonus=mod(c.attrs[chk.ability]||10);const total=d+bonus;const ok=total>=chk.dc;$('die').textContent=`d20: ${d}`;$('rollResult').innerHTML=`${esc(c.name)} ${fmt(bonus)} = <strong>${total}</strong> — <span class="${ok?'pass':'fail'}">${ok?'SUCESSO':'FALHA'}</span>`;state.pendingCheck=null;setTimeout(()=>{state.node=ok?chk.success:chk.failure;renderNode()},650)}
function quickDie(){const type=+$('dieType').value;const r=Math.floor(Math.random()*type)+1;alert(`d${type}: ${r}`)}
function saveGame(){const payload={characters:state.characters,active:state.active,node:state.node,flags:state.flags};localStorage.setItem('valedouro.save.q01',JSON.stringify(payload))}
function resumeGame(){try{const s=JSON.parse(localStorage.getItem('valedouro.save.q01')||'null');if(!s)throw 0;state.characters=s.characters||[];state.active=s.active||0;state.node=s.node||Q01.start;state.flags=s.flags||{};state.quest=Q01;$('party').innerHTML=state.characters.map((c,i)=>`<div class="pc ${i===state.active?'selected':''}" onclick="selectPC(${i})"><strong>${esc(c.name)}</strong><small>${esc(c.cls)}</small><small>CA ${c.ca} • PV ${c.hp}/${c.hpMax}</small></div>`).join('');$('story').innerHTML='';show('game');selectPC(state.active);renderNode()}catch{alert('Nenhum jogo salvo encontrado.')}}
function resetSave(){localStorage.removeItem('valedouro.save.q01');alert('Save da Q01 removido.')}
window.addEventListener('DOMContentLoaded',()=>{loadChars();playerCount()});
